# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'EL-UI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EL-UI
  pod 'GoogleMLKit/Translate', '3.2.0'

end
